services:
  zui-docs:
    build:
      context: .
      dockerfile: Dockerfile
    image: zui-docs
    container_name: zui-docs
    ports:
      - '4173:80'
    environment:
      - TZ=Asia/Shanghai
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/']
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - baota_net

networks:
  baota_net:
    external: true

#  docker compose down
#  docker compose up -d --build
#  docker logs -f zui-docs
